### PR TITLE
fix: eliminate rosdep errors

### PR DESCRIPTION
**Pull request by bgilby59**
## Description

Stop having rosdep try to install unnecessary packages to eliminate rosdep errors, and revert autoware.universe back to a commit that allow edge-auto to build without error.

## Tests performed

Reran rosdep install and build script. Confirmed that both ran without errors.

## Effects on system behavior

Now edge-auto builds and rosdep does not output error messages.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by bgilby59** [comment]
I changed the autoware.universe version back to "main" in autoware.repos.

**Review by drwnz — APPROVED** [review]
LGTM!

**Comment by drwnz** [comment]
@bgilby59 can you please resolve the conflicts on this PR?

**Comment by bgilby59** [comment]
@drwnz Conflicts are resolved. I want to note that this PR effectively reverts [this PR](https://github.com/tier4/edge-auto/commit/25ee4500be413421b53f215bfb5ec0106053b431), but this is intentional to reduce the dependencies stored in autoware.repos. Good to merge?

**Review by drwnz — APPROVED** [review]
LGTM

**Pull request merged**
