### PR TITLE
feat: lightNet-TRTのROS2ラッパーの実装

### PR DESCRIPTION
**Pull request by chickenta2ta**
[lightNet-TRT](https://github.com/daniel89710/lightNet-TRT)のROS2ラッパーです。edge-auto-jetson上で動きます。画像を受け取るとdetection + segmentationされた画像を返すだけで、bounding boxなどは返さないミニマルな実装になっています（元リポジトリではbboxも出すので、今後拡張可能）。

変更が複数リポジトリに及ぶため、各リポジトリにどのような変更を加えたか以下に記載します。
- 本リポジトリ: ドキュメンテーションのみ
- [edge-auto-jetson](https://github.com/tier4/edge-auto-jetson/pull/37): `experimental.repos`にlightNet-TRTをクローンしてくる記述を追加
- [edge_auto_jetson_launch](https://github.com/tier4/edge_auto_jetson_launch/pull/9): 既存のパッケージを`ros2 launch`する際、`tensorrt_lightnet_is_installed:=true`の引数を渡すとlightNet-TRTを起動するようにlaunchファイルを修正
- [edge-auto-tensorrt-lightnet](https://github.com/tier4/edge-auto-tensorrt-lightnet): ROSラッパー部分のメインのコードが入っているリポジトリ。新規リポジトリのため、PRはありません

---

落ちているciについては、今回手を入れた箇所で落ちるようになった訳ではないため未対応

### CODE REVIEW

**Comment by chickenta2ta** [comment]
三浦さんと平林さんのフィードバックをベースに、以下の要領でPR修正しました。

- 蓑田さん開発のlightNet-TRTのROSパッケージに乗っかる形に変更
- [experimental.reposには上記リポジトリのURLを記載](https://github.com/tier4/edge-auto-jetson/pull/37)
- [edge_auto_jetson_launchへの変更は取り下げ](https://github.com/tier4/edge_auto_jetson_launch/pull/9)
- [lightNet-TRT側のREADME](https://github.com/kminoda/lightNet-TRT-ROS2)にインストール方法を記載し、edge-auto側のdocsではREADMEへのリンクのみ記載

また、[lightNet-TRTのCMakeLists](https://github.com/kminoda/lightNet-TRT-ROS2)を使ってedge-auto上でROSパッケージをビルドするとboost filesystemがリンクできずエラーになるため、[find_packageを追記するPR](https://github.com/kminoda/lightNet-TRT-ROS2/pull/9)も併せて出しています。

**Comment by manato** [comment]
@chickenta2ta 
Thank you very much for your great contribution. I'm trying to reproduce the procedure of this PR, however, I've not made it work yet, unfortunately.
As far as I checked, the default  `.weight` file (i.e., `yolov8x-BDD100K-640x640-T4-lane4cls-scratch-pseudo-finetune_last.weights`) looks missing anywhere. Do you download it manually or do you have another branch where it is contained?
If you download it manually, I'd appreciate it if you add your procedure to the document. Or if you have another branch, it would be nice to specify the branch explicitly in the `.repos` file. Thanks!

**Comment by chickenta2ta** [comment]
@manato 
Thank you very much for checking the reproducibility of this PR.
As you pointed out, the procedure of downloading the weights file is missing.
I added a step to manually download the file to [the README file](https://github.com/kminoda/lightNet-TRT-ROS2/pull/10/).
I appreciate if you could check it again.

---

Since this PR requires another PR (in Minoda-san's repository) to be merged, I'll write down the steps to reproduce this PR before all PRs are merged into main.

1. In `experimental.repos`, change url to `https://github.com/chickenta2ta/lightNet-TRT-ROS2` and version to `feature/add-to-edgeauto-docs`. This step will be unnecessary when [this PR](https://github.com/kminoda/lightNet-TRT-ROS2/pull/10) is merged.
2. Download the weights file and build the package according to [the documentation](https://github.com/chickenta2ta/lightNet-TRT-ROS2/tree/feature/add-to-edgeauto-docs). When launching the node, please note that lightNet-TRT is for images with 1280x960 resolution.

---

Also, I'll write down PRs that are relavant to this PR.
- This PR: modification only on docs
- [edge-auto-jetson](https://github.com/tier4/edge-auto-jetson/pull/37): `experimental.repos` is modified
- [lightNet-TRT-ROS2](https://github.com/kminoda/lightNet-TRT-ROS2/pull/10): launch file and install documentation

**Review by manato — APPROVED** [review]
By following your instructions, I've confirmed the module looks working. Thank you very much for your contribution! 
image

**Pull request merged**
